### ISSUE TITLE
I cant compile the app

### ISSUE THREAD

**Issue by dvdrbls** [janivanecky/builder#1]
This is the message I got trying to build Physarum

$ "C:\Users\Dell\Desktop\Physarum\builder-master\bin\build.exe" physarum.build
No files match pattern '../cpplib', line 0.
Expected at least one directory in 'include_dir' command. Line 0.
No files match pattern '../cpplib/third_party/freetype/include', line 1.
Expected at least one directory in 'include_dir' command. Line 1.
No files match pattern '../cpplib/ui.cpp', line 2.
Expected at least one source file in 'build_exe' command. Line 2.
Uncrecognized identifier '../cpplib/maths.cpp'.
Uncrecognized identifier '../cpplib/graphics.cpp'.
Uncrecognized identifier '../cpplib/font.cpp'.
Uncrecognized identifier '../cpplib/memory.cpp'.
Uncrecognized identifier '../cpplib/input.cpp'.
Uncrecognized identifier '../cpplib/file_system.cpp'.
Uncrecognized identifier '../cpplib/platform.cpp'.
No files match pattern '../cpplib/fonts/*', line 4.
Expected at least one source file in 'copy' command. Line 4.
No files match pattern '../cpplib/freetype/win64/freetype271MT.dll', line 5.
Expected at least one source file in 'copy' command. Line 5.
Need to specify at least full 'build_exe' command - build_exe($exe_name, $source_files)

Dell@DESKTOP-5ULCN0I MINGW32 /c/users/dell/desktop/physarum

what can I do to make it work?
Thanks!

**Comment by janivanecky** [comment]
Hey, sorry for replying so late.

Looks like a path problem. Do you have `cpplib` folder in `C:/users/dell/desktop`?

**Comment by dvdrbls** [comment]
Thank you for reply

I think the problem is since the build step, look

C:\Users\Dell\Desktop\Physarum\builder>build.bat

C:\Users\Dell\Desktop\Physarum\builder>if not exist "bin" mkdir bin

C:\Users\Dell\Desktop\Physarum\builder>if not exist "bin\\obj" mkdir bin\\obj

C:\Users\Dell\Desktop\Physarum\builder>call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.29
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
main.cpp
c:\users\dell\desktop\physarum\builder\microsoft_craziness.h(213): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
c:\users\dell\desktop\physarum\builder\microsoft_craziness.h(216): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data
c:\users\dell\desktop\physarum\builder\microsoft_craziness.h(480): warning C4244: 'argument': conversion from 'LONGLONG' to 'int', possible loss of data
c:\users\dell\desktop\physarum\builder\config.h(28): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
c:\users\dell\desktop\physarum\builder\config.h(34): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
c:\users\dell\desktop\physarum\builder\config.h(42): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
c:\users\dell\desktop\physarum\builder\config.h(51): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
c:\users\dell\desktop\physarum\builder\config.h(30): warning C4996: 'wcstombs': This function or variable may be unsafe. Consider using wcstombs_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\stdlib.h(1015): note: see declaration of 'wcstombs'
c:\users\dell\desktop\physarum\builder\config.h(36): warning C4996: 'wcstombs': This function or variable may be unsafe. Consider using wcstombs_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\stdlib.h(1015): note: see declaration of 'wcstombs'
c:\users\dell\desktop\physarum\builder\config.h(44): warning C4996: 'wcstombs': This function or variable may be unsafe. Consider using wcstombs_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\stdlib.h(1015): note: see declaration of 'wcstombs'
c:\users\dell\desktop\physarum\builder\config.h(53): warning C4996: 'wcstombs': This function or variable may be unsafe. Consider using wcstombs_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt\stdlib.h(1015): note: see declaration of 'wcstombs'

C:\Users\Dell\Desktop\Physarum\builder>

I did create a Physarum folder and started cloning inside of it, so theres a builder folder a cpplib folder and a physarum builder too 

if I double click it instead of using the console this error just flashes and the screen closes

**Comment by janivanecky** [comment]
Ah, so the way I understand your directory structure is this (correct me if I'm wrong):

`.../Desktop/Physarum` directory contains:

- `builder` directory
- `cpplib` directory
- directly contains Physarum repo, so e.g. `physarum.build` file

In case that's right, you have to modify `physarum.build` so that all the mentions of `../cpplib` path are just `cpplib`. The build file assumes that `cpplib` is going to be one directory up from the build file, not in the same directory.

Does that make sense?

**Comment by dvdrbls** [comment]
Thank you!
I was able to build the app

C:\Users\Dell\Desktop\physarum2>builder\bin\build.exe physarum.build
Source files:
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe C:\Users\Dell\Desktop\physarum2\main.cpp C:\Users\Dell\Desktop\physarum2\cpplib\ui.cpp C:\Users\Dell\Desktop\physarum2\cpplib\maths.cpp C:\Users\Dell\Desktop\physarum2\cpplib\graphics.cpp C:\Users\Dell\Desktop\physarum2\cpplib\font.cpp C:\Users\Dell\Desktop\physarum2\cpplib\memory.cpp C:\Users\Dell\Desktop\physarum2\cpplib\input.cpp C:\Users\Dell\Desktop\physarum2\cpplib\file_system.cpp C:\Users\Dell\Desktop\physarum2\cpplib\platform.cpp C:\Users\Dell\Desktop\physarum2\cpplib\ui_draw.cpp /I C:\Users\Dell\Desktop\physarum2\cpplib /I C:\Users\Dell\Desktop\physarum2\cpplib\third_party\freetype\include /nologo /W3 /Od /RTC1 /MTd /EHsc /Zc:inline /Gm- /MP /Fo:bin\obj\ /Fdbin\ /Zi /DDEBUG /link /INCREMENTAL:NO /subsystem:console /MACHINE:X64 /debug:fastlink /CGTHREADS:4 kernel32.lib user32.lib gdi32.lib D3D11.lib dxguid.lib d3dcompiler.lib DXGI.lib XAudio2.lib Ole32.lib cpplib/third_party/freetype/win64/freetype271MT.lib Winmm.lib  /OUT:bin\physarum.exe
main.cpp
ui.cpp
maths.cpp
graphics.cpp
font.cpp
memory.cpp
input.cpp
file_system.cpp
platform.cpp
ui_draw.cpp
C:\Users\Dell\Desktop\physarum2\main.cpp(264): warning C4244: '=': conversion from 'uint32_t' to 'float', possible loss of data
C:\Users\Dell\Desktop\physarum2\main.cpp(265): warning C4244: '=': conversion from 'uint32_t' to 'float', possible loss of data
C:\Users\Dell\Desktop\physarum2\main.cpp(266): warning C4244: '=': conversion from 'uint32_t' to 'float', possible loss of data
C:\Users\Dell\Desktop\physarum2\main.cpp(267): warning C4244: '=': conversion from 'uint32_t' to 'float', possible loss of data
C:\Users\Dell\Desktop\physarum2\main.cpp(268): warning C4244: '=': conversion from 'uint32_t' to 'float', possible loss of data
C:\Users\Dell\Desktop\physarum2\main.cpp(552): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
C:\Users\Dell\Desktop\physarum2\main.cpp(557): warning C4244: '=': conversion from 'double' to 'float', possible loss of data
C:\Users\Dell\Desktop\physarum2\main.cpp(598): warning C4305: 'argument': truncation from 'double' to 'float'
C:\Users\Dell\Desktop\physarum2\main.cpp(599): warning C4244: 'initializing': conversion from 'int' to 'float', possible loss of data
Compilation done! (1.826151s)
> physarum.exe

The app runs, should I ignore this warnings or those had to be with the functionality?
by the way the graphics are awesome, thank you!

**Comment by janivanecky** [comment]
You can just ignore the warnings :) Enjoy!
